version: "3"

services:

  backend:
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - ./backend_app:/app

  frontend:
    command: npm start
    environment:
      - API_URL=http://0.0.0.0:5000/
    volumes:
      - ./frontend_app:/app
      - /app/node_modules
